//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSQRScan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"^XA

^FO10,20
^ADN,36,20
^FDModel:^FS

^FO170,20
^ADN,30,20
^FD[MODEL]^FS

^FO58,60
^ADN,36,20
^FDS/N:^FS

^FO170,60
^ADN,30,20
^FD[SN]^FS

^FO60,100
^BQN,2,4
^FDMM,A#@[MODEL]@$[SN]$%[DATE]%#^FS

^FO200,110
^BXN,6,200
^FDO1970A1CS^FS

^XZ
")]
        public string zebraCode {
            get {
                return ((string)(this["zebraCode"]));
            }
            set {
                this["zebraCode"] = value;
            }
        }
    }
}
